version: 2

sphinx:
    configuration: src/docs/conf.py  # Укажите путь к конфигурационному файлу Sphinx

python:
    install:
        - requirements: doc_reqs.txt  # Файл с зависимостями

build:
    os: ubuntu-22.04  # Операционная система
    tools:
        python: "3.10"  # Версия Python

# Параметры для сборки документации
commands:
    - cd src/docs && make html  # Заходим в директорию и выполняем make html