version: 2

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
build:
     os: ubuntu-22.04
     tools:
        python: "3.10"  # Указание версии Python
     commands:
        - pip install -r requirements.txt
        - pip install sphinx sphinx_rtd_theme
#         - python setup.py install  # Установка пакета (если это необходимо)
        - cd src
        - mkdir docs
        - cd docs  # Переходим в директорию с документацией
        - sphinx-quickstart
        - make html  # Генерация HTML