version: 2

sphinx:
  configuration: src/docs/conf.py

python:
  install:
    - requirements: requirements.txt
build:
     os: ubuntu-22.04
     tools:
        python: "3.10"  # Указание версии Python
     commands:
        - python setup.py install  # Установка пакета (если это необходимо)