from .msa_fuzzy_pareto import fuzzy_pareto_solver
from .msa_fuzzy_sum import fuzzy_sum_solver
from .msa_fuzzy_pairwise import fuzzy_pairwise_solver
from .msa_fuzzy_hierarchy import fuzzy_hierarchy_solver
